# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add_book_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Add_Book_Dialog(object):
    def setupUi(self, Add_Book_Dialog):
        Add_Book_Dialog.setObjectName("Add_Book_Dialog")
        Add_Book_Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Add_Book_Dialog.resize(768, 461)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Add_Book_Dialog.sizePolicy().hasHeightForWidth())
        Add_Book_Dialog.setSizePolicy(sizePolicy)
        Add_Book_Dialog.setSizeGripEnabled(True)
        Add_Book_Dialog.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(Add_Book_Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Add_Book_Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Add_Book_Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Add_Book_Dialog)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.b_back = QtWidgets.QPushButton(Add_Book_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_back.sizePolicy().hasHeightForWidth())
        self.b_back.setSizePolicy(sizePolicy)
        self.b_back.setMinimumSize(QtCore.QSize(50, 0))
        self.b_back.setObjectName("b_back")
        self.gridLayout.addWidget(self.b_back, 0, 3, 1, 1)
        self.b_add_book = QtWidgets.QPushButton(Add_Book_Dialog)
        self.b_add_book.setObjectName("b_add_book")
        self.gridLayout.addWidget(self.b_add_book, 3, 2, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(Add_Book_Dialog)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setRowCount(200)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 4)
        self.b_del_book = QtWidgets.QPushButton(Add_Book_Dialog)
        self.b_del_book.setMinimumSize(QtCore.QSize(110, 0))
        self.b_del_book.setObjectName("b_del_book")
        self.gridLayout.addWidget(self.b_del_book, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Add_Book_Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Add_Book_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Add_Book_Dialog)

    def retranslateUi(self, Add_Book_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Add_Book_Dialog.setWindowTitle(_translate("Add_Book_Dialog", "Добавление сценария"))
        self.label.setText(_translate("Add_Book_Dialog", "Выберите сценарий"))
        self.b_back.setText(_translate("Add_Book_Dialog", "Назад"))
        self.b_add_book.setText(_translate("Add_Book_Dialog", "Сохранить этот сценарий"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Add_Book_Dialog", "Время,с"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Add_Book_Dialog", "Давление,\n"
"бар"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Add_Book_Dialog", "КЭ1"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Add_Book_Dialog", "КЭ2"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Add_Book_Dialog", "КЭ3"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Add_Book_Dialog", "КЭ4"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Add_Book_Dialog", "КЭ5"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Add_Book_Dialog", "КЭ6"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Add_Book_Dialog", "ЭД1"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Add_Book_Dialog", "ЭД2"))
        self.b_del_book.setText(_translate("Add_Book_Dialog", "Удалить сценарий"))
        self.label_2.setText(_translate("Add_Book_Dialog", "<html><head/><body><p align=\"center\">Имя сценария</p></body></html>"))

