# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'My_1_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Stand(object):
    def setupUi(self, Stand):
        Stand.setObjectName("Stand")
        Stand.resize(1172, 914)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Stand.sizePolicy().hasHeightForWidth())
        Stand.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Stand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_save_graf = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_save_graf.sizePolicy().hasHeightForWidth())
        self.b_save_graf.setSizePolicy(sizePolicy)
        self.b_save_graf.setMinimumSize(QtCore.QSize(150, 0))
        self.b_save_graf.setObjectName("b_save_graf")
        self.horizontalLayout_3.addWidget(self.b_save_graf)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.b_discharge = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_discharge.sizePolicy().hasHeightForWidth())
        self.b_discharge.setSizePolicy(sizePolicy)
        self.b_discharge.setMinimumSize(QtCore.QSize(75, 20))
        self.b_discharge.setObjectName("b_discharge")
        self.horizontalLayout_3.addWidget(self.b_discharge)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.b_start_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_start_1.sizePolicy().hasHeightForWidth())
        self.b_start_1.setSizePolicy(sizePolicy)
        self.b_start_1.setMinimumSize(QtCore.QSize(75, 20))
        self.b_start_1.setObjectName("b_start_1")
        self.horizontalLayout_3.addWidget(self.b_start_1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.b_stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_stop.sizePolicy().hasHeightForWidth())
        self.b_stop.setSizePolicy(sizePolicy)
        self.b_stop.setMinimumSize(QtCore.QSize(75, 20))
        self.b_stop.setObjectName("b_stop")
        self.horizontalLayout_3.addWidget(self.b_stop)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, -1, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(3)
        self.gridLayout_5.setVerticalSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_5.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_5.addWidget(self.lineEdit_10, 4, 3, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_5.addWidget(self.lineEdit_9, 3, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_5.addWidget(self.lineEdit_5, 5, 1, 1, 1)
        self.l_engine1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_engine1.sizePolicy().hasHeightForWidth())
        self.l_engine1.setSizePolicy(sizePolicy)
        self.l_engine1.setMinimumSize(QtCore.QSize(75, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_engine1.setFont(font)
        self.l_engine1.setObjectName("l_engine1")
        self.gridLayout_5.addWidget(self.l_engine1, 4, 2, 1, 1)
        self.l_level_liquid = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_level_liquid.sizePolicy().hasHeightForWidth())
        self.l_level_liquid.setSizePolicy(sizePolicy)
        self.l_level_liquid.setMinimumSize(QtCore.QSize(75, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_level_liquid.setFont(font)
        self.l_level_liquid.setObjectName("l_level_liquid")
        self.gridLayout_5.addWidget(self.l_level_liquid, 3, 2, 1, 1)
        self.l_temperature = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_temperature.sizePolicy().hasHeightForWidth())
        self.l_temperature.setSizePolicy(sizePolicy)
        self.l_temperature.setMinimumSize(QtCore.QSize(75, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_temperature.setFont(font)
        self.l_temperature.setObjectName("l_temperature")
        self.gridLayout_5.addWidget(self.l_temperature, 2, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_5.addWidget(self.lineEdit_8, 2, 3, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_5.addWidget(self.lineEdit_7, 1, 3, 1, 1)
        self.l_valve3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_valve3.sizePolicy().hasHeightForWidth())
        self.l_valve3.setSizePolicy(sizePolicy)
        self.l_valve3.setMinimumSize(QtCore.QSize(57, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_valve3.setFont(font)
        self.l_valve3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_valve3.setObjectName("l_valve3")
        self.gridLayout_5.addWidget(self.l_valve3, 3, 0, 1, 1)
        self.l_valve2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_valve2.sizePolicy().hasHeightForWidth())
        self.l_valve2.setSizePolicy(sizePolicy)
        self.l_valve2.setMinimumSize(QtCore.QSize(57, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_valve2.setFont(font)
        self.l_valve2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_valve2.setObjectName("l_valve2")
        self.gridLayout_5.addWidget(self.l_valve2, 2, 0, 1, 1)
        self.l_valve5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_valve5.sizePolicy().hasHeightForWidth())
        self.l_valve5.setSizePolicy(sizePolicy)
        self.l_valve5.setMinimumSize(QtCore.QSize(57, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_valve5.setFont(font)
        self.l_valve5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_valve5.setObjectName("l_valve5")
        self.gridLayout_5.addWidget(self.l_valve5, 5, 0, 1, 1)
        self.l_valve6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_valve6.sizePolicy().hasHeightForWidth())
        self.l_valve6.setSizePolicy(sizePolicy)
        self.l_valve6.setMinimumSize(QtCore.QSize(57, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_valve6.setFont(font)
        self.l_valve6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_valve6.setObjectName("l_valve6")
        self.gridLayout_5.addWidget(self.l_valve6, 6, 0, 1, 1)
        self.l_valve4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_valve4.sizePolicy().hasHeightForWidth())
        self.l_valve4.setSizePolicy(sizePolicy)
        self.l_valve4.setMinimumSize(QtCore.QSize(57, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_valve4.setFont(font)
        self.l_valve4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_valve4.setObjectName("l_valve4")
        self.gridLayout_5.addWidget(self.l_valve4, 4, 0, 1, 1)
        self.l_pressure = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_pressure.sizePolicy().hasHeightForWidth())
        self.l_pressure.setSizePolicy(sizePolicy)
        self.l_pressure.setMinimumSize(QtCore.QSize(75, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_pressure.setFont(font)
        self.l_pressure.setObjectName("l_pressure")
        self.gridLayout_5.addWidget(self.l_pressure, 1, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_5.addWidget(self.lineEdit_6, 6, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.l_valve1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_valve1.sizePolicy().hasHeightForWidth())
        self.l_valve1.setSizePolicy(sizePolicy)
        self.l_valve1.setMinimumSize(QtCore.QSize(57, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_valve1.setFont(font)
        self.l_valve1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_valve1.setObjectName("l_valve1")
        self.gridLayout_5.addWidget(self.l_valve1, 1, 0, 1, 1)
        self.l_time = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_time.sizePolicy().hasHeightForWidth())
        self.l_time.setSizePolicy(sizePolicy)
        self.l_time.setMinimumSize(QtCore.QSize(57, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_time.setFont(font)
        self.l_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_time.setObjectName("l_time")
        self.gridLayout_5.addWidget(self.l_time, 7, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_5.addWidget(self.lineEdit_12, 7, 1, 1, 1)
        self.l_engine2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_engine2.sizePolicy().hasHeightForWidth())
        self.l_engine2.setSizePolicy(sizePolicy)
        self.l_engine2.setMinimumSize(QtCore.QSize(75, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_engine2.setFont(font)
        self.l_engine2.setObjectName("l_engine2")
        self.gridLayout_5.addWidget(self.l_engine2, 6, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_5.addWidget(self.lineEdit_11, 6, 3, 1, 1)
        self.l_engine2_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_engine2_2.sizePolicy().hasHeightForWidth())
        self.l_engine2_2.setSizePolicy(sizePolicy)
        self.l_engine2_2.setMinimumSize(QtCore.QSize(75, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_engine2_2.setFont(font)
        self.l_engine2_2.setObjectName("l_engine2_2")
        self.gridLayout_5.addWidget(self.l_engine2_2, 7, 2, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_13.setSizePolicy(sizePolicy)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_5.addWidget(self.lineEdit_13, 7, 3, 1, 1)
        self.l_engine2_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_engine2_3.sizePolicy().hasHeightForWidth())
        self.l_engine2_3.setSizePolicy(sizePolicy)
        self.l_engine2_3.setMinimumSize(QtCore.QSize(75, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_engine2_3.setFont(font)
        self.l_engine2_3.setObjectName("l_engine2_3")
        self.gridLayout_5.addWidget(self.l_engine2_3, 5, 2, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_5.addWidget(self.lineEdit_14, 5, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.b_add_model = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_add_model.sizePolicy().hasHeightForWidth())
        self.b_add_model.setSizePolicy(sizePolicy)
        self.b_add_model.setMinimumSize(QtCore.QSize(150, 0))
        self.b_add_model.setObjectName("b_add_model")
        self.gridLayout.addWidget(self.b_add_model, 11, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(150, 15))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 9, 0, 1, 1)
        self.b_models = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_models.sizePolicy().hasHeightForWidth())
        self.b_models.setSizePolicy(sizePolicy)
        self.b_models.setMinimumSize(QtCore.QSize(150, 20))
        self.b_models.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.b_models.setObjectName("b_models")
        self.gridLayout.addWidget(self.b_models, 10, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(190, 107))
        self.textBrowser.setMaximumSize(QtCore.QSize(190, 115))
        self.textBrowser.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 6, 1, 5, 1)
        self.b_load_book = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_load_book.sizePolicy().hasHeightForWidth())
        self.b_load_book.setSizePolicy(sizePolicy)
        self.b_load_book.setMinimumSize(QtCore.QSize(190, 0))
        self.b_load_book.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.b_load_book.setCheckable(False)
        self.b_load_book.setObjectName("b_load_book")
        self.gridLayout.addWidget(self.b_load_book, 11, 1, 1, 1)
        self.b_graf = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_graf.sizePolicy().hasHeightForWidth())
        self.b_graf.setSizePolicy(sizePolicy)
        self.b_graf.setMinimumSize(QtCore.QSize(190, 20))
        self.b_graf.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.b_graf.setObjectName("b_graf")
        self.gridLayout.addWidget(self.b_graf, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(190, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 1, 1, 1)
        self.b_disconnect = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_disconnect.sizePolicy().hasHeightForWidth())
        self.b_disconnect.setSizePolicy(sizePolicy)
        self.b_disconnect.setMinimumSize(QtCore.QSize(150, 0))
        self.b_disconnect.setObjectName("b_disconnect")
        self.gridLayout.addWidget(self.b_disconnect, 5, 0, 1, 1)
        self.b_books = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_books.sizePolicy().hasHeightForWidth())
        self.b_books.setSizePolicy(sizePolicy)
        self.b_books.setMinimumSize(QtCore.QSize(150, 0))
        self.b_books.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.b_books.setObjectName("b_books")
        self.gridLayout.addWidget(self.b_books, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(150, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.b_add_book = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_add_book.sizePolicy().hasHeightForWidth())
        self.b_add_book.setSizePolicy(sizePolicy)
        self.b_add_book.setMinimumSize(QtCore.QSize(150, 0))
        self.b_add_book.setObjectName("b_add_book")
        self.gridLayout.addWidget(self.b_add_book, 8, 0, 1, 1)
        self.b_updateComPorts = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_updateComPorts.sizePolicy().hasHeightForWidth())
        self.b_updateComPorts.setSizePolicy(sizePolicy)
        self.b_updateComPorts.setMinimumSize(QtCore.QSize(150, 0))
        self.b_updateComPorts.setObjectName("b_updateComPorts")
        self.gridLayout.addWidget(self.b_updateComPorts, 3, 0, 1, 1)
        self.b_connect = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_connect.sizePolicy().hasHeightForWidth())
        self.b_connect.setSizePolicy(sizePolicy)
        self.b_connect.setMinimumSize(QtCore.QSize(150, 0))
        self.b_connect.setObjectName("b_connect")
        self.gridLayout.addWidget(self.b_connect, 2, 0, 1, 1)
        self.b_comPorts = QtWidgets.QComboBox(self.centralwidget)
        self.b_comPorts.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_comPorts.sizePolicy().hasHeightForWidth())
        self.b_comPorts.setSizePolicy(sizePolicy)
        self.b_comPorts.setMinimumSize(QtCore.QSize(190, 0))
        self.b_comPorts.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.b_comPorts.setObjectName("b_comPorts")
        self.gridLayout.addWidget(self.b_comPorts, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 4)
        self.l_zetlab = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_zetlab.sizePolicy().hasHeightForWidth())
        self.l_zetlab.setSizePolicy(sizePolicy)
        self.l_zetlab.setMinimumSize(QtCore.QSize(57, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_zetlab.setFont(font)
        self.l_zetlab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_zetlab.setObjectName("l_zetlab")
        self.gridLayout_5.addWidget(self.l_zetlab, 8, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_5.addWidget(self.lineEdit_15, 8, 1, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_16.sizePolicy().hasHeightForWidth())
        self.lineEdit_16.setSizePolicy(sizePolicy)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(60, 24))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_5.addWidget(self.lineEdit_16, 8, 3, 1, 1)
        self.l_zetlab_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_zetlab_2.sizePolicy().hasHeightForWidth())
        self.l_zetlab_2.setSizePolicy(sizePolicy)
        self.l_zetlab_2.setMinimumSize(QtCore.QSize(75, 28))
        self.l_zetlab_2.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_zetlab_2.setFont(font)
        self.l_zetlab_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_zetlab_2.setObjectName("l_zetlab_2")
        self.gridLayout_5.addWidget(self.l_zetlab_2, 8, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.w_plot1 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_plot1.sizePolicy().hasHeightForWidth())
        self.w_plot1.setSizePolicy(sizePolicy)
        self.w_plot1.setMinimumSize(QtCore.QSize(800, 0))
        self.w_plot1.setObjectName("w_plot1")
        self.verticalLayout_2.addWidget(self.w_plot1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_8.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(619, 20))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.w_plot2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_plot2.sizePolicy().hasHeightForWidth())
        self.w_plot2.setSizePolicy(sizePolicy)
        self.w_plot2.setMinimumSize(QtCore.QSize(800, 0))
        self.w_plot2.setObjectName("w_plot2")
        self.gridLayout_8.addWidget(self.w_plot2, 2, 0, 1, 1)
        Stand.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Stand)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1172, 21))
        self.menuBar.setObjectName("menuBar")
        self.MyMenu = QtWidgets.QMenu(self.menuBar)
        self.MyMenu.setObjectName("MyMenu")
        Stand.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.MyMenu.menuAction())

        self.retranslateUi(Stand)
        QtCore.QMetaObject.connectSlotsByName(Stand)

    def retranslateUi(self, Stand):
        _translate = QtCore.QCoreApplication.translate
        Stand.setWindowTitle(_translate("Stand", "Программа управления стендом"))
        self.b_save_graf.setText(_translate("Stand", "Сохранить график"))
        self.b_discharge.setText(_translate("Stand", "СЛИВ"))
        self.b_start_1.setText(_translate("Stand", "ЗАПУСК"))
        self.b_stop.setText(_translate("Stand", "СТОП"))
        self.lineEdit_4.setText(_translate("Stand", "Недоступен"))
        self.lineEdit_10.setText(_translate("Stand", "Недоступен"))
        self.lineEdit_9.setText(_translate("Stand", "Недоступен"))
        self.lineEdit_2.setText(_translate("Stand", "Недоступен"))
        self.lineEdit.setText(_translate("Stand", "Недоступен"))
        self.lineEdit_5.setText(_translate("Stand", "Недоступен"))
        self.l_engine1.setText(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Крутящий </p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">момент </p></body></html>"))
        self.l_level_liquid.setText(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Уровень </p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">жидкости </p></body></html>"))
        self.l_temperature.setText(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Текущая t </p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">жидкости </p></body></html>"))
        self.lineEdit_8.setText(_translate("Stand", "Недоступен"))
        self.lineEdit_7.setText(_translate("Stand", "Недоступен"))
        self.l_valve3.setText(_translate("Stand", "Клапан 3"))
        self.l_valve2.setText(_translate("Stand", "Клапан 2"))
        self.l_valve5.setText(_translate("Stand", "Клапан 5"))
        self.l_valve6.setText(_translate("Stand", "Клапан 6"))
        self.l_valve4.setText(_translate("Stand", "Клапан 4"))
        self.l_pressure.setText(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Давление на </p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">выходе РД </p></body></html>"))
        self.lineEdit_6.setText(_translate("Stand", "Недоступен"))
        self.lineEdit_3.setText(_translate("Stand", "Недоступен"))
        self.l_valve1.setText(_translate("Stand", "Клапан 1"))
        self.l_time.setText(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Время</p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">испытания</p></body></html>"))
        self.lineEdit_12.setText(_translate("Stand", "Недоступен"))
        self.l_engine2.setText(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Электро- </p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">двигатель 1 </p></body></html>"))
        self.lineEdit_11.setText(_translate("Stand", "Недоступен"))
        self.l_engine2_2.setText(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Электро- </p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">двигатель 2 </p></body></html>"))
        self.lineEdit_13.setText(_translate("Stand", "Недоступен"))
        self.l_engine2_3.setText(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Средняя t </p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">жидкости </p></body></html>"))
        self.lineEdit_14.setText(_translate("Stand", "Недоступен"))
        self.b_add_model.setText(_translate("Stand", "Создать эталонную модель"))
        self.label_4.setText(_translate("Stand", "<html><head/><body><p align=\"center\">Выбор эталонной модели</p></body></html>"))
        self.textBrowser.setHtml(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.b_load_book.setText(_translate("Stand", "Отправить сценарий"))
        self.label_8.setText(_translate("Stand", "Выбор тестируемой модели"))
        self.b_disconnect.setText(_translate("Stand", "Отключиться"))
        self.label_6.setText(_translate("Stand", "Выбор сценария"))
        self.b_add_book.setText(_translate("Stand", "Редактировать сценарий"))
        self.b_updateComPorts.setText(_translate("Stand", "Обновить список устройств"))
        self.b_connect.setText(_translate("Stand", "Подключиться "))
        self.l_zetlab.setText(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Связь с</p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ZETLAB</p></body></html>"))
        self.lineEdit_15.setText(_translate("Stand", "Недоступен"))
        self.lineEdit_16.setText(_translate("Stand", "Недоступен"))
        self.l_zetlab_2.setText(_translate("Stand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Связь с РД</p>\n"
""))
        self.label_7.setText(_translate("Stand", "Программа управления стендом"))
        self.MyMenu.setTitle(_translate("Stand", "Меню"))
